version: "3.8"

services:
  muda-frontend:
    stdin_open: true
    tty: true
    network_mode: host
    container_name: muda-frontend-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - muda-frontend-data:/ibicos-frontend/node_modules
    image: muda-frontend:dev

volumes:
  muda-frontend-data:
