version: "3.8"

services:
  agricultura-familiar:
    build:
      context: .
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/agricultura_familiar_db
      - MYSQL-USER=
      - MUDA_EMAIL_PASSWORD=
      - MUDA_EMAIL_USERNAME=
      - SECURITY_ENABLED=true
      - SECURITY_SIGNING_KEY=abacate
      - SECURITY_TOKEN_VALIDITY_IN_MINUTES=60

    volumes:
      - ./:/agricultura_familiar_backend
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=agricultura_familiar_db
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

volumes:
  mysql_data:
  mysql_config:
