name: Frontend Deploy

defaults:
  run:
    working-directory: ./frontend/agricultura-familiar

on:
  push:
    branches:
      - issue34/feature
    paths:
      - "frontend/agricultura-familiar/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and build
        run: npm ci
      - run: npm run build
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_FRONTEND}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "frontend/agricultura-familiar"
