name: Frontend Deploy

defaults:
  run:
    working-directory: ./frontend/agricultura-familiar

on:
  push:
    branches:
      - issue34/feature

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_FRONTEND}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "frontend/agricultura-familiar"
